print("mulletrpc!")
local_resource("lint", ["poetry", "run", "flake8", "app", "mulletrpc.py"])
local_resource("black", ["poetry", "run", "black", "--check", "app", "mulletrpc.py"])
local_resource("isort", ["poetry", "run", "isort", "--check-only", "app", "mulletrpc.py"])
docker_build('mulletrpc', '.')
k8s_yaml('local_dev/local.yaml')
k8s_resource('mulletrpc', port_forwards=8080)
