---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mulletrpc-pv-claim
  labels:
    app: mulletrpc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mulletrpc
  labels:
    app: mulletrpc
spec:
  selector:
    matchLabels:
      app: mulletrpc
  template:
    metadata:
      labels:
        app: mulletrpc
    spec:
      containers:
        - name: mulletrpc
          image: mulletrpc
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLIENT_SECRET
            - name: REDIRECT_URI 
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIRECT_URI
            - name: ISSUER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ISSUER
            - name: TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TOKEN_URI
            - name: AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH_URI
            - name: USERINFO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: USERINFO_URI
            - name: TOKEN_INTROSPECTION_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TOKEN_INTROSPECTION_URI
            - name: DATABASE_URL 
              value: sqlite:////db/app.db
          ports:
            - containerPort: 5000 
          volumeMounts:
          - name: persistent-storage
            mountPath: /db
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mulletrpc-pv-claim            
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default 
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mulletrpc-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces", "events"]
  verbs: ["get", "watch", "list", "log"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mulletrpc-pod-reader
subjects:
- kind: ServiceAccount
  name: default 
  namespace: default 
roleRef:
  kind: ClusterRole
  name: mulletrpc-pod-reader
  apiGroup: rbac.authorization.k8s.io
